apiVersion: apps/v1
kind: Deployment
metadata:
  name: abnitio-etl-component
  namespace: dev-ns
spec:
  selector:
    matchLabels:
        app: abnitio-etl-component
  template:
    metadata:
      labels:
        app: abnitio-etl-component1
    spec:
      restartPolicy: Always
      containers:
        - name: abnitio-etl-component
          image: "{{ .Values.imagedata.name }}:{{ .Values.imagedata.tag }}"
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]

        
