apiVersion: apps/v1
kind: Deployment
metadata:
  name: abnitio-etl-component
spec:
  replicas:1
  selector:
    matchLabels:
      app: abnitio-etl-component
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: abnitio-etl-component
    spec:
      restartPolicy: Never
      containers:
      - image: <+artifact.image>
        imagePullPolicy: IfNotPresent
        name: abnitio-etl-component
        ports:
        - containerPort: 80