apiVersion: apps/v1
kind: Deployment
metadata:
  name: abnitio-etl-component1
  namespace: dev-ns
spec:
  selector:
    matchLabels:
        app: abnitio-etl-component
  template:
    metadata:
      labels:
        app: abnitio-etl-component
    spec:
      restartPolicy: Always
      containers:
        - name: abnitio-etl-component
          image: docker.io/bindumounica87/etl-component:graph-user-flow-v1.1.1
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]

        
