apiVersion: batch/v1
kind: Job
metadata:
  name: abnitio-etl-component
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: abnitio-etl-component
    spec:
      restartPolicy: Never
      containers:
      - name: abnitio-etl-component 
        image: docker.io/bindumounica87/etl-component:graph-user-flow-v1.1.1
        imagePullPolicy: IfNotPresent
        command: ["sleep", "infinity"]
        ports:
        - containerPort: 80