apiVersion: batch/v1
kind: Job
metadata:
  name: abnitio-etl-component
  namespace: dev-ns
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: abnitio-etl-component
    spec:
      restartPolicy: Never
      containers:
        - name: abnitio-etl-component
          image: <+serviceVariables.Image_name>:<+serviceVariables.Image_tag>
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]

        
